debug: true
spring:
  application:
    name: democlient
  thymeleaf:
    encoding: utf-8
    cache: false
server:
  port: 8762
#eureka:
#  instance:
#    #主机名称
#    #hostname: 192.168.8.116
#    hostname: eurekaserver
#    #是否使用IP地址的形式，如果设置了eureka.instance.ip-address 属性，则使用该属性配置的IP，否则自动获取除环路IP外的第一个IP地址
#    preferIpAddress: true
#    #ip地址
#    ipAddress: eurekaserver
#    #定义服务续约任务（心跳）的调用间隔，默认值:30秒
#    leaseRenewalIntervalInSeconds: 10
#    #定义服务失效的时间，默认值:90秒
#    leaseExpirationDurationInSeconds: 30
#  client:
#    healthcheck:
#      #开启健康检查
#      enabled: true
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8760/eureka/